import { AnimatePresence, motion } from 'framer-motion'
import { CheckCircle2, FileImage, FileText, ScanLine, ShieldCheck, Upload, X } from 'lucide-react'
import { useRef, useState } from 'react'
import PageTransition from '../components/PageTransition'

export default function UploadPrescription() {
  const [file, setFile] = useState(null); const [state, setState] = useState('idle'); const input = useRef()
  const select = value => { if (!value) return; setFile(value); setState('ready') }
  const extract = () => {setState('processing');setTimeout(() => setState('complete'), 1400)}
  return <PageTransition className="upload-page page-width"><section className="upload-heading"><span className="eyebrow"><ScanLine size={14}/> Prescription upload</span><h1>Let your prescription<br/><em>do the talking.</em></h1><p>Upload a clear photo. We’ll help organize the details so you can search and compare with ease.</p></section><section className="upload-shell">{state !== 'complete' ? <><div className={`drop-zone ${file ? 'has-file' : ''}`} onClick={() => input.current.click()} onDragOver={e => e.preventDefault()} onDrop={e => {e.preventDefault();select(e.dataTransfer.files?.[0])}}>{file ? <div className="file-selected"><span className="file-thumb"><FileImage size={25}/></span><div><strong>{file.name}</strong><small>{Math.ceil(file.size/1024) || 240} KB · Ready to extract</small></div><button onClick={e => {e.stopPropagation();setFile(null);setState('idle')}}><X size={16}/></button></div> : <><span className="upload-icon"><Upload size={25}/></span><h2>Drop your prescription here</h2><p>or <b>browse your files</b></p><small>PNG, JPG, PDF · up to 10 MB</small></>}<input ref={input} onChange={e => select(e.target.files?.[0])} type="file" accept="image/*,.pdf" hidden/></div>{state === 'ready' && <button className="button button-dark extract-button" onClick={extract}>Extract medicines <ScanLine size={17}/></button>}{state === 'processing' && <div className="extracting"><span><ScanLine size={21}/></span><div><strong>Reading your prescription</strong><p>Finding medicine names and strengths…</p><i><b/></i></div></div>}<div className="upload-assurance"><ShieldCheck size={18}/><span>Your upload is used only to process this request.</span></div></> : <ExtractionResult/>}</section></PageTransition>
}
function ExtractionResult() { return <motion.div className="extraction-result" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}><span className="success-mark"><CheckCircle2 size={26}/></span><span className="eyebrow">Extraction complete</span><h2>We found 3 medicines</h2><p>Review each item before you explore your options.</p><div className="extracted-list">{[['Dolo 650','Paracetamol 650 mg'],['Pantocid 40','Pantoprazole 40 mg'],['Cetirizine 10','Cetirizine 10 mg']].map(([name,salt]) => <div key={name}><FileText size={17}/><span><strong>{name}</strong><small>{salt}</small></span><CheckCircle2 size={17}/></div>)}</div><button className="button button-dark">View medicine choices</button></motion.div> }
